name: starlight
description: "A fast and modern editor."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  window_manager: ^0.4.2
  provider: ^6.1.2
  macos_ui: ^2.0.9
  async: ^2.11.0
  uuid: ^4.5.0
  xterm: ^4.0.0
  flutter_pty: ^0.4.1
  shared_preferences: ^2.3.2
  desktop_drop: ^0.5.0
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  fonts:
    - family: SF Mono
      fonts:
        - asset: assets/Fonts/SanFrancisco/SF-Mono-Regular.otf
          weight: 400
        - asset: assets/Fonts/SanFrancisco/SF-Mono-Medium.otf
          weight: 500
    - family: SF Pro Display
      fonts:
        - asset: assets/Fonts/SanFrancisco/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/Fonts/SanFrancisco/SF-Pro-Display-RegularItalic.otf
          style: italic
          weight: 400
  uses-material-design: true
  assets:
    - assets/
